services:
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - eccomerce-backend-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ecommerce_rabbit
    ports:
      - '5672:5672'
      - '15672:15672' 
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eccomerce-backend-network

  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    container_name: catalog_service
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - eccomerce-backend-network

  orders-service:
    build:
      context: ./orders-service
      dockerfile: Dockerfile
    container_name: orders_service
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - eccomerce-backend-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    environment:
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
      PORT: ${GATEWAY_PORT}
    ports:
      - '${GATEWAY_PORT}:${GATEWAY_PORT}'
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - eccomerce-backend-network

  eccomerce-app:
    build:
      context: ./ecommerce-app
      dockerfile: Dockerfile
    container_name: ecommerce-app
    environment:
      NEXT_PUBLIC_API_URL: ${API_GATEWAY}
    ports:
      - ${FRONT_PORT}:3003
    depends_on:
      api-gateway:
        condition: service_started
    networks:
      - eccomerce-backend-network

volumes:
  postgres_data:

networks:
  eccomerce-backend-network:
    driver: bridge
